### ISSUE TITLE
Fail to load Studio components

### ISSUE THREAD

**Issue by ThomasSaout** [instabase/blueprint-oss#10]
Hello, I try to launch studio but there is a problem

all seem to launch fine, front  and back server running .

No error log but web browser only shows blank page Hello, I am trying to launch the studio but it was a problem

all seem to launch fine, front and back server running.

No error log but web browser only shows blank page when i resuqest http://<host>:3000/

still some warning about deprecated usage  
```
 (node:31444) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] (node:31444) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use the async 'start' or 'startCallback' method.
```

the list of library version is 
```
$ npm vers
{
  studio: '3.1.3',
  npm: '6.14.17',
  ares: '1.18.1',
  brotli: '1.0.9',
  cldr: '41.0',
  icu: '71.1',
  llhttp: '6.0.10',
  modules: '108',
  napi: '8',
  nghttp2: '1.47.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  node: '18.12.1',
  openssl: '3.0.7+quic',
  tz: '2022b',
  unicode: '14.0',
  uv: '1.43.0',
  v8: '10.2.154.15-node.12',
  zlib: '1.2.11'
}
```
do you have any leads for me

**Comment by andmis** [comment]
Hi Thomas,

Could you please post a screenshot of the issue you are having (a screenshot of Studio in the error state).

Also, please open the Chrome Dev Tools (⌥⌘J in Chrome) and paste any log/error data in the Dev Tools Console.

Also please paste the contents of your terminal, both from the Studio front-end terminal as well as the back-end terminal output.

And I'll take a look!
Thanks

**Comment by ThomasSaout** [comment]
log from front terminal :
```
$ npm start

> studio@3.1.3 start
> concurrently 'yarn start-dev-server' 'yarn type-check-watch'

yarn run v1.22.19
yarn run v1.22.19
$ yarn type-check --watch --preserveWatchOutput
$ webpack serve --mode development
$ tsc --watch --preserveWatchOutput
[1]
[1] 09:30:05 - Starting compilation in watch mode...
[1]
[0] <w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
[0] (node:32151) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] (node:32151) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use the async 'start' or 'startCallback' method.
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/
[0] <i> [webpack-dev-server] On Your Network (IPv4): http://10.254.254.253:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/root/blueprint-oss/studio/static/' directory
[1]
[1] 09:30:12 - Found 0 errors. Watching for file changes.
[0] asset bundle.js 2.11 MiB [emitted] (name: main) 1 related asset
[0] runtime modules 25.5 KiB 11 modules
[0] orphan modules 15.9 KiB [orphan] 10 modules
[0] cacheable modules 1.71 MiB
[0]   modules by path ./src/ 473 KiB
[0]     modules by path ./src/components/ 297 KiB 93 modules
[0]     modules by path ./src/util/*.ts 22.3 KiB 14 modules
[0]     modules by path ./src/hooks/ 27.3 KiB 14 modules
[0]     modules by path ./src/foundation/*.ts 24.3 KiB 10 modules
[0]     modules by path ./src/state/*.ts 49.8 KiB 8 modules
[0]     modules by path ./src/blueprint/*.ts 20.4 KiB 8 modules
[0]     modules by path ./src/async/*.ts 26.6 KiB 7 modules
[0]     modules by path ./src/context/*.tsx 1.11 KiB 5 modules
[0]     modules by path ./src/accuracy/*.ts 3.9 KiB 2 modules
[0]     ./src/main.tsx 334 bytes [built] [code generated]
[0]   modules by path ./node_modules/ 1.25 MiB 138 modules
[0] webpack 5.30.0 compiled successfully in 11785 ms

```
from back terminal 
```
$ python -m bp_server
 * Serving Flask app '__main__'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.254.254.253:5000
Press CTRL+C to quit
```
the browser and the Chrome DevTools
![studio_and_term](https://user-images.githubusercontent.com/73241894/205005719-e5abd383-3847-41c5-adb8-d285edcdfc9c.PNG)

for launch front i need to change webpack.config.js : 
```
  devServer: {
    static: path.join(__dirname, 'static/'),
    port: 3000,
    compress: true,
    client: {
      logging: 'info',
    },
  },
```
this change is from this issue [#2958](https://github.com/webpack/webpack-dev-server/issues/2958)

**Comment by andmis** [comment]
Normally the `devServer` part of `config.webpack.js` says:
```
  devServer: {
    contentBase: path.join(__dirname, 'static/'),
    port: 3000,
    publicPath: 'http://localhost:3000/',
  },
```

What happens if you try starting the front-end _without_ changing `config.webpack.js`?

**Comment by andmis** [comment]
I just tried installing everything from scratch. I had to do `npm upgrade webpack` in `studio/` because of [this bug](https://github.com/webpack/webpack/issues/14532). But then everything worked for me.

**Comment by ThomasSaout** [comment]
i try from scratch too and make `npm upgrade webpack` and i get that log error, that was solve by the modification on `config.webpack.js`
```
$ npm start

> studio@3.1.3 start
> concurrently 'yarn start-dev-server' 'yarn type-check-watch'

yarn run v1.22.19
yarn run v1.22.19
$ yarn type-check --watch --preserveWatchOutput
$ webpack serve --mode development
$ tsc --watch --preserveWatchOutput
[1]
[1] 15:41:08 - Starting compilation in watch mode...
[1]
[0] [webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
[0]  - options has an unknown property 'publicPath'. These properties are valid:
[0]    object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] yarn start-dev-server exited with code 2
[1]
[1] 15:41:14 - Found 0 errors. Watching for file changes.

```
could you send me log of `npm vers` 

Thank you for your time

**Comment by andmis** [comment]
```
{
  studio: '3.1.3',
  npm: '8.19.3',
  node: '19.2.0',
  v8: '10.8.168.20-node.8',
  uv: '1.44.2',
  zlib: '1.2.13',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '111',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '8.1.0',
  openssl: '3.0.7+quic',
  cldr: '42.0',
  icu: '72.1',
  tz: '2022f',
  unicode: '15.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}
```

**Comment by andmis** [comment]
It seems like you're probably using a different version of some of the Node modules from what we're using -- otherwise I don't see why you would be getting those errors, if we had the same versions.

Changing the config file to make the error message go away isn't necessarily a "fix" unless everything else still works. I suspect your change didn't really fully fix the problem.

**Comment by andmis** [comment]
Can you try changing the `devServer` part of `config.webpack.js` to say:
```
  devServer: {
    contentBase: path.join(__dirname, 'static/'),
    port: 3000,
    devMiddleware: {
        publicPath: 'http://localhost:3000/',
    },
  },
```

**Comment by ThomasSaout** [comment]
Hello, 

After some search i found this config
```
devServer: {
    contentBase: path.join(__dirname, 'static/'),
    port: 3000,
    publicPath: 'http://localhost:3000/',
    host: '0.0.0.0',
  },
```
I want to launch studio in a VM and use it from another computer in the same network. 

With this config the first page is correctly generating that seem to solve my first trouble. 

But when doing that i get an exception from OnClick  
```
Beginning create new project interaction
App.tsx:258 Uncaught TypeError: window.showDirectoryPicker is not a function
    at onClick (App.tsx:258:20)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306:1)
    at executeDispatch (react-dom.development.js:389:1)
    at executeDispatchesInOrder (react-dom.development.js:414:1)
    at executeDispatchesAndRelease (react-dom.development.js:3278:1)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3287:1)
    at forEachAccumulated (react-dom.development.js:3259:1)
react-dom.development.js:327 Uncaught TypeError: window.showDirectoryPicker is not a function
    at onClick (App.tsx:258:20)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306:1)
    at executeDispatch (react-dom.development.js:389:1)
    at executeDispatchesInOrder (react-dom.development.js:414:1)
    at executeDispatchesAndRelease (react-dom.development.js:3278:1)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3287:1)
    at forEachAccumulated (react-dom.development.js:3259:1)
```
Thank you for you help i will tag this issue closed.

**Comment by andmis** [comment]
Did you manage to get things running?

**Comment by ThomasSaout** [comment]
Yes i can run it on local, but i didn't had reach state where i can run it from remote yet.

**Comment by ThomasSaout** [comment]
> Can you try changing the `devServer` part of `config.webpack.js` to say:
> 
> ```
>   devServer: {
>     contentBase: path.join(__dirname, 'static/'),
>     port: 3000,
>     devMiddleware: {
>         publicPath: 'http://localhost:3000/',
>     },
>   },
> ```

this change didn't solve my trouble with remote call of onClick()

**Comment by andmis** [comment]
What's going wrong? A couple of things to try:
- You might need to configure the backend to use `0.0.0.0` (instead of `localhost` or `127.0.0.1`) to access it remotely.
- You might need to configure the command to run the front-end dev server in some special way for the frontend to be accessible remotely.
- You could also try compiling the frontend, instead of running it from a dev server.

**Comment by ThomasSaout** [comment]
Actually the frontend work remotly, i will try configure backend and keep you informed

**Comment by ThomasSaout** [comment]
Hello i made some progress. 

i found `window.showOpenFilePicker()` only work in local or need a secure context, from [here](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API)

> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility).

`devServer ` part of my `config.webpack.js` look like :

```
 devServer: {
    https: true,
    contentBase: path.join(__dirname, 'static/'),
    port: 3000,
    publicPath: 'https://localhost:3000/',
    host: '0.0.0.0',
  },
```
Currently i have trouble with some urls who need to be dynamicly set, i will try to solve that and i think the solution will work remotly 

![studio](https://user-images.githubusercontent.com/73241894/208108428-3b316617-fafa-47c1-826b-cfea0f634939.PNG)

**Comment by andmis** [comment]
I’m curious, why do you want it to work remotely?

**Comment by ThomasSaout** [comment]
Hello, 

I made a lot of progress, they work remotly, we need to authorize unknow certificat for the site `https://<ip_server>:<port>/ `
 in browser, and next step is to set dynamic call to backend ip. 
 
To answer your curiosity, my thesis is about extracting information from invoices, it is co-financed by a company and I need to show them that constraint solving can be used to extract data. The best solution to convince them is to let them handle exceptional tools based on this concept.

**Comment by andmis** [comment]
Great! Let us know if you have more problems.
